# Generated by Django 4.1.1 on 2022-10-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormroom',
            old_name='resHallId',
            new_name='resHall',
        ),
        migrations.RenameField(
            model_name='dormroomphoto',
            old_name='dormRoomId',
            new_name='dormRoom',
        ),
        migrations.RenameField(
            model_name='dormroomreview',
            old_name='dormRoomId',
            new_name='dormRoom',
        ),
        migrations.RenameField(
            model_name='reshall',
            old_name='universityId',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='reshallphoto',
            old_name='resHallId',
            new_name='resHall',
        ),
        migrations.RenameField(
            model_name='reshallreview',
            old_name='resHallId',
            new_name='resHall',
        ),
    ]
