# Generated by Django 4.1.1 on 2022-12-02 23:07

from django.db import migrations

# create test data for database upon initial "python manage.py migrate" command
def createTestData(apps, schema_editor):
    
    # get models from app
    university = apps.get_model('dormapp', 'University')
    resHall = apps.get_model('dormapp', 'ResHall')
    dormRoom = apps.get_model('dormapp', 'DormRoom')
    resHallReview = apps.get_model('dormapp', 'ResHallReview')
    resHallPhoto = apps.get_model('dormapp', 'ResHallPhoto')
    dormRoomReview = apps.get_model('dormapp', 'DormRoomReview')
    dormRoomPhoto = apps.get_model('dormapp', 'DormRoomPhoto')

    # create universities
    syracuseU = university.objects.create(name='Syracuse University')
    cornellU = university.objects.create(name='Cornell University')

    # create Syracuse University residence halls
    shawHall = resHall.objects.create(name='Shaw Hall', university=syracuseU)
    boothHall = resHall.objects.create(name='Booth Hall', university=syracuseU)
    
    # create Syracuse University dorm rooms
    shaw463 = dormRoom.objects.create(roomNumber='463', resHall=shawHall)
    shaw309 = dormRoom.objects.create(roomNumber='309', resHall=shawHall)

    # create Cornell University dorms
    smithHall = resHall.objects.create(name='Smith Hall', university=cornellU)
    smith261 = dormRoom.objects.create(roomNumber='261', resHall=smithHall)
    
    # create residence hall reviews
    shawReview1 = resHallReview.objects.create(
        reviewTitle = 'Pretty good dorm',
        reviewBody = 'Has a dining hall but too many engineers',
        starRating = 3,
        resHall = shawHall
    )
    boothReview1 = resHallReview.objects.create(
        reviewTitle = 'Good for sophomores',
        reviewBody = 'Close to campus but the walk is steep',
        starRating = 4,
        resHall = boothHall
    )

    # create residence hall photos
    shawPhoto1 = resHallPhoto.objects.create(
        photo = 'res-hall-photos/test_data_shaw.jpg',
        resHall = shawHall
    )
    shawPhoto2 = resHallPhoto.objects.create(
        photo = 'res-hall-photos/test_data_shaw2.jpg',
        resHall = shawHall
    )
    boothPhoto1 = resHallPhoto.objects.create(
        photo = 'res-hall-photos/test_data_booth.jpg',
        resHall = boothHall
    )

    # create dorm room reviews
    shaw463Review1 = dormRoomReview.objects.create(
        reviewTitle = 'Big room',
        reviewBody = 'Long elevator ride though',
        starRating = 3,
        dormRoom = shaw463,
    )
    shaw463Review2 = dormRoomReview.objects.create(
        reviewTitle = 'Cool residents',
        reviewBody = '',
        starRating = 5,
        dormRoom = shaw463
    )
    
    # create dorm room photos
    shaw463Photo1 = dormRoomPhoto.objects.create(
        photo = 'dorm-room-photos/test_data_shaw463.jpg',
        dormRoom = shaw463
    )

class Migration(migrations.Migration):

    dependencies = [
        ('dormapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(createTestData)
    ]
