# Generated by Django 4.1.1 on 2022-10-05 20:36

from django.db import migrations
import uuid

suUuid = uuid.uuid4()

def initUniversities(apps, schema_editor):
    universityModel = apps.get_model('dormapp', 'University')
    resHallModel = apps.get_model('dormapp', 'ResHall')

    universityModel.objects.create (
        id = suUuid,
        name = 'Syracuse University'
        )
    resHallModel.objects.create (
        id = uuid.uuid4(),
        name = 'Booth Hall',
        university = universityModel.objects.first()
    )
    resHallModel.objects.create (
        id = uuid.uuid4(),
        name = 'Shaw Hall',
        university = universityModel.objects.first()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dormapp', '0002_rename_reshallid_dormroom_reshall_and_more'),
    ]

    operations = [
        
        migrations.RunPython(initUniversities),

    ]
