# Generated by Django 4.1.1 on 2022-12-08 02:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dormapp', '0002_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='university-photos')),
                ('dateCreated', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormapp.university')),
            ],
        ),
    ]
