# Generated by Django 4.1.1 on 2022-10-10 20:50

from django.db import migrations

def initResHallPhotos(apps,schema_editor):
    resHallModel = apps.get_model('dormapp','ResHall')
    resHallPhotoModel = apps.get_model('dormapp','ResHallPhoto')

    resHallPhotoModel.objects.create(
        resHall = resHallModel.objects.all()[0],
        photo = 'res-hall-photos/booth.jpg'
    )

    resHallPhotoModel.objects.create(
        resHall = resHallModel.objects.all()[1],
        photo = 'res-hall-photos/shaw.jpg'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('dormapp', '0004_dormroomphoto_datecreated_dormroomreview_datecreated_and_more'),
    ]

    operations = [
        migrations.RunPython(initResHallPhotos)
    ]
