# Generated by Django 4.1.1 on 2022-10-12 20:30

from django.db import migrations
import uuid

def addReviews(apps, schema_editor):
    resHallModel = apps.get_model('dormapp', 'ResHall')
    resHallReviewModel = apps.get_model('dormapp', 'ResHallReview')

    shaw = resHallModel.objects.filter(name='Shaw Hall')[0]

    resHallReviewModel.objects.create(
        id = uuid.uuid4(),
        resHall = shaw,
        starRating = 3,
        reviewTitle = 'My Shaw Review Title',
        reviewBody = 'shaw review body'
    )
    resHallReviewModel.objects.create(
        id = uuid.uuid4(),
        resHall = shaw,
        starRating = 4,
        reviewTitle = 'Second Shaw Review Title',
        reviewBody = 'second shaw review body'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('dormapp', '0006_hotswapping_migration_5'),
    ]

    operations = [
        
        migrations.RunPython(addReviews),

    ]

