# Generated by Django 4.1.1 on 2022-10-20 01:07

from django.db import migrations
import uuid

def addDormRooms(apps, schema_editor):
    resHallModel = apps.get_model('dormapp', 'ResHall')
    dormRoomModel = apps.get_model('dormapp', 'DormRoom')

    shaw = resHallModel.objects.filter(name='Shaw Hall')[0]
    
    dormRoomModel.objects.create(
        id = uuid.uuid4(),
        resHall = shaw,
        roomNumber = '463'
    )
    dormRoomModel.objects.create(
        id = uuid.uuid4(),
        resHall = shaw,
        roomNumber = '534'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('dormapp', '0007_addReviews'),
    ]

    operations = [
        migrations.RunPython(addDormRooms),
    ]
