# Generated by Django 4.1.1 on 2022-11-06 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormapp', '0008_addDormRoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormroomphoto',
            name='dormRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormapp.dormroom'),
        ),
    ]
